typography_spectrum: 0.8255319
color:
  saturation: 0.4692176308017224
  brandStrength: 0.3680821792222559
  rhythmicContrast: 0.9623335746582597
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  lightness: 0.5319781769067049
layout_spectrum: 0.1562289877329022
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/614d22e7-033b-4496-a968-a70119c6608b.jpg
name: Raconteur Sound
navigation:
  - name: Portfolio
    url: 'http://thegrid.ai/rs-portfolio/'
    type: external
  - name: Sound Effects
    url: 'http://www.sonniss.com/vendor/clechner/'
    type: external
  - name: Field Recording Kit
    id: 88bb2503-f8fd-447b-ae15-72991cc2108b
    type: content
  - name: Studio
    id: 1a30ea6e-62e5-410c-82f7-c5dc209ee602
    type: content
  - name: Collaborators
    id: 1224b806-b781-4b65-ad4b-4541f3b38113
    type: content
  - name: Contact Us
    id: f59f16df-e057-455c-94e2-6deb7ffb29a7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e0a2a24-1965-4726-aafe-3cee50d42c0f.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Raconteur Sound
description: Helping the world hear your story.
