typography_spectrum: 0.8255319
color:
  saturation: 0.4692176308017224
  brandStrength: 0.3680821792222559
  rhythmicContrast: 0.9623335746582597
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  lightness: 0.5319781769067049
layout_spectrum: 0.1562289877329022
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f06e2cf9-69a9-460d-ac08-cbe2b6690898.png
name: Raconteur Sound
navigation:
  - id: 'http://thegrid.ai/rs-portfolio/'
    url: 'http://thegrid.ai/rs-portfolio/'
    name: Portfolio
    type: external
  - id: 'http://www.sonniss.com/vendor/clechner/'
    url: 'http://www.sonniss.com/vendor/clechner/'
    name: Sound Effects
    type: external
  - id: 1224b806-b781-4b65-ad4b-4541f3b38113
    url: 2016-07-19-collaborators.html
    name: Collaborators
    type: content
  - id: 1a30ea6e-62e5-410c-82f7-c5dc209ee602
    url: 2016-03-16-studio.html
    name: Studio
    type: content
  - id: 88bb2503-f8fd-447b-ae15-72991cc2108b
    url: 2016-06-11-field-recording-equipment.html
    name: Field Recording Kit
    type: content
  - id: f59f16df-e057-455c-94e2-6deb7ffb29a7
    url: 2016-07-20-contact-us.html
    name: Contact Us
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e0a2a24-1965-4726-aafe-3cee50d42c0f.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
