collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8255319
color:
  saturation: 0.4692176308017224
  brandStrength: 0.3680821792222559
  rhythmicContrast: 0.9623335746582597
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  lightness: 0.5319781769067049
layout_spectrum: 0.1562289877329022
name: Raconteursound
navigation:
  - id: 88bb2503-f8fd-447b-ae15-72991cc2108b
    url: 2016-06-11-field-recording-equipment.html
    name: Field Recording Kit
    type: content
  - id: 'http://thegrid.ai/rs-portfolio/'
    url: 'http://thegrid.ai/rs-portfolio/'
    name: Portfolio
    type: external
