typography_spectrum: 0.16437100642360747
color:
  saturation: 0.30977790080942214
  brandStrength: 0.1438666491303593
  rhythmicContrast: 0.37974782078526914
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  lightness: 0.9105561543256044
layout_spectrum: 0.012489593122154474
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/614d22e7-033b-4496-a968-a70119c6608b.jpg
name: Raconteur Sound
navigation:
  - name: Portfolio
    url: 'http://thegrid.ai/rs-portfolio/'
    type: external
  - name: Sound Effects
    url: 'http://www.sonniss.com/vendor/clechner/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e0a2a24-1965-4726-aafe-3cee50d42c0f.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
description: ''
